variables:
  	AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    AWS_BUCKET_URL: $AWS_BUCKET_URL

stages:
  - build
  - deploy

build:
  stage: build
  image: node:14
  only:
    - trunk
  script:
    - npm ci
    - CI=false npm run build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  image: python:3.8
  script:
    - pip install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws s3 sync build/ AWS_BUCKET_URL